Repository DeveloperAcademy-POSTECH/MC3-Team3-AllerView, pull requests merged in 2023-07, with the labels that each got.

#2 CoreData Entity Modeling
  AllerView/AllerView.xcdatamodeld/AllerView.xcdatamodel/contents
Labels: feat

#8 Add CoreData CRUD
  AllerView.xcodeproj/project.pbxproj
  AllerView/Extension/Allergy+CoreData.swift
  AllerView/Extension/Keyword+CoreData.swift
  AllerView/Extension/User+CoreData.swift
  AllerView/Extension/ViewContext+Entity.swift
Labels: feat

#14 Change CoreData Modeling
  AllerView.xcodeproj/project.pbxproj
  AllerView/AllerView.xcdatamodeld/AllerView.xcdatamodel/contents
  AllerView/Extension/Allergy+CoreData.swift
  AllerView/Extension/User+CoreData.swift
  AllerView/Extension/ViewContext+Entity.swift
Labels: feat

#12 Add CameraView Scanning Features
  .gitattributes
  .gitignore
  AllerView.xcodeproj/project.pbxproj
  AllerView/Assets.xcassets/icon_flash_off.imageset/Contents.json
  AllerView/Assets.xcassets/icon_flash_off.imageset/icon_flash_off.png
  AllerView/Assets.xcassets/icon_flash_on.imageset/Contents.json
  AllerView/Assets.xcassets/icon_flash_on.imageset/icon_flash_on.png
  AllerView/CameraView.swift
Labels: feat

#15 Apply CoreData schema changes
  AllerView.xcodeproj/project.pbxproj
  AllerView/AllerViewApp.swift
  AllerView/AllergeSearch/AllergySearchView.swift
  AllerView/Extension/ViewContext+Entity.swift
Labels: feat

#11 Add ContentView
  AllerView.xcodeproj/project.pbxproj
  AllerView/Chip.swift
  AllerView/ContentView.swift
  AllerView/DummyData.swift
Labels: feat

#18 Link All Views & Features
  AllerView.xcodeproj/project.pbxproj
  AllerView.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  AllerView.xcodeproj/xcshareddata/xcschemes/AllerView.xcscheme
  AllerView/AllerViewApp.swift
  AllerView/Assets.xcassets/blackLongBarcord.imageset/Contents.json
  AllerView/Assets.xcassets/blackLongBarcord.imageset/blackLongBarcord 1.png
  AllerView/Assets.xcassets/blackLongBarcord.imageset/blackLongBarcord 2.png
  AllerView/Assets.xcassets/blackLongBarcord.imageset/blackLongBarcord.png
  AllerView/Component/Chip.swift
  AllerView/ContentView.swift
  AllerView/Extension/Keyword+CoreData.swift
  AllerView/Extension/ViewContext+Entity.swift
  AllerView/View/AllergySearchView.swift
  AllerView/View/CameraView.swift
  AllerView/View/ContentView.swift
Labels: feat

#21 Applying dummy data for UserTest
  AllerView.xcodeproj/project.pbxproj
  AllerView/Assets.xcassets/Haribo.imageset/Contents.json
  AllerView/Assets.xcassets/Haribo.imageset/Haribo.png
  AllerView/Assets.xcassets/LotteSand.imageset/Contents.json
  AllerView/Assets.xcassets/LotteSand.imageset/LotteSand.png
  AllerView/Assets.xcassets/Saewooggang.imageset/Contents.json
  AllerView/Assets.xcassets/Saewooggang.imageset/Saewooggang.png
  AllerView/Component/Chip.swift
  AllerView/DummyData.swift
  AllerView/View/AllergySearchView.swift
  AllerView/View/CameraView.swift
  AllerView/View/ContentView.swift
Labels: feat

#24 Improvement Design
  AllerView/DummyData.swift
  AllerView/View/AllergySearchView.swift
  AllerView/View/CameraView.swift
  AllerView/View/ContentView.swift
  AllerView/View/ProductDetailView.swift
Labels: refactor

#29 Refactor AllergySearchView and add Colors
  AllerView/Component/Chip.swift
  AllerView/Component/Colors.swift
  AllerView/View/AllergySearchView.swift
  AllerView/View/ProductDetailView.swift
Labels: feat, refactor

#31 refactor(AllergySearchView): remove animation, adjust padding
  AllerView.xcodeproj/project.pbxproj
  AllerView/View/AllergySearchView.swift
Labels: refactor

#32 TextDetection and highlight using VisionKit
  AllerView.xcodeproj/project.pbxproj
  AllerView.xcodeproj/xcshareddata/xcschemes/AllerView.xcscheme
  AllerView/AllerViewApp.swift
  AllerView/Assets.xcassets/my_allergy_btn.imageset/Contents.json
  AllerView/Assets.xcassets/my_allergy_btn.imageset/my_allergy_btn.png
  AllerView/Assets.xcassets/testFinal2.imageset/Contents.json
  AllerView/Assets.xcassets/testFinal2.imageset/IMG_5890.jpeg
  AllerView/Utility/ImageUtility.swift
  AllerView/Utility/VisionUtility.swift
  AllerView/View/CameraView.swift
  AllerView/View/ContentView.swift
  AllerView/View/ImageCropView.swift
  AllerView/View/MainView.swift
  AllerView/View/ScannerView.swift
  AllerViewTests/VisionUtilityTests.swift
Labels: feat

#34 Refactor CameraView Features
  AllerView.xcodeproj/project.pbxproj
  AllerView/View/ScannerView.swift
Labels: refactor

#33 Refactor(AllergySearchView): remove chip scroll, add shadow
  AllerView.xcodeproj/project.pbxproj
  AllerView.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  AllerView/View/AllergySearchView.swift
Labels: refactor

#35 Add chat GPT Manager
  AllerView.xcodeproj/project.pbxproj
  AllerView.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  AllerView/Constants.swift
  AllerView/GPTViewModel.swift
  AllerView/Model/GPTModel.swift
  AllerView/OpenAIService.swift
  AllerView/View/ContentView.swift
  AllerView/View/GPTView.swift
Labels: feat

#37 Improve chatGPT Prompt
  .gitignore
  AllerView.xcodeproj/project.pbxproj
  AllerView.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  AllerView/Service/OpenAIService.swift
Labels: feat
