Repository DeveloperAcademy-POSTECH/MC3-Team3-AllerView, pull requests merged in 2023-08, with the labels that each got.

#46 Change the views with a modified design
  AllerView.xcodeproj/project.pbxproj
  AllerView.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  AllerView/AllerView.xcdatamodeld/AllerView.xcdatamodel/contents
  AllerView/AllerViewApp.swift
  AllerView/Assets.xcassets/AIHead.imageset/AIHead.png
  AllerView/Component/Chip.swift
  AllerView/Extension/ViewContext+Entity.swift
  AllerView/Resource/Assets.xcassets/AIHead.imageset/Contents.json
  AllerView/Resource/Assets.xcassets/AIHead.imageset/Group 37.png
  AllerView/Resource/Assets.xcassets/AccentColor.colorset/Contents.json
  AllerView/Resource/Assets.xcassets/AppIcon.appiconset/Contents.json
  AllerView/Resource/Assets.xcassets/AppIcon.appiconset/Group 74.png
  AllerView/Resource/Assets.xcassets/Contents.json
  AllerView/Resource/Assets.xcassets/Haribo.imageset/Contents.json
  AllerView/Resource/Assets.xcassets/Haribo.imageset/Haribo.png
  AllerView/Resource/Assets.xcassets/LotteSand.imageset/Contents.json
  AllerView/Resource/Assets.xcassets/LotteSand.imageset/LotteSand.png
  AllerView/Resource/Assets.xcassets/Saewooggang.imageset/Contents.json
  AllerView/Resource/Assets.xcassets/Saewooggang.imageset/Saewooggang.png
  AllerView/Resource/Assets.xcassets/blackLongBarcord.imageset/Contents.json
  AllerView/Resource/Assets.xcassets/blackLongBarcord.imageset/blackLongBarcord 1.png
  AllerView/Resource/Assets.xcassets/blackLongBarcord.imageset/blackLongBarcord 2.png
  AllerView/Resource/Assets.xcassets/blackLongBarcord.imageset/blackLongBarcord.png
  AllerView/Resource/Assets.xcassets/icon_flash_off.imageset/Contents.json
  AllerView/Resource/Assets.xcassets/icon_flash_off.imageset/icon_falsh_off.png
  AllerView/Resource/Assets.xcassets/icon_flash_on.imageset/Contents.json
  AllerView/Resource/Assets.xcassets/icon_flash_on.imageset/icon_flash_on.png
  AllerView/Resource/Assets.xcassets/my_allergy_btn.imageset/Contents.json
  AllerView/Resource/Assets.xcassets/my_allergy_btn.imageset/my_allergy_btn.png
  AllerView/Resource/Assets.xcassets/testFinal2.imageset/Contents.json
  AllerView/Resource/Assets.xcassets/testFinal2.imageset/IMG_5890.jpeg
  AllerView/Resource/Loading.json
  AllerView/View/AllergyDetailView.swift
  AllerView/View/AllergySearchView.swift
  AllerView/View/ContentView.swift
  AllerView/View/ImageCropView.swift
  AllerView/View/LoadingView.swift
  AllerView/View/Model/CameraViewModel.swift
  AllerView/View/Model/GPTModel.swift
  AllerView/View/ScannerView.swift
Labels: refactor

#42 Block Landscape Mode
  AllerView.xcodeproj/project.pbxproj
Labels: feat

#48 Modify ScannerView GUI
  AllerView/View/ScannerView.swift
Labels: refactor

#52 Modify Crop Box to Allow Only Rectangles
  AllerView/View/ImageCropView.swift
Labels: feat

#54 Modify GPT Prompts and Add FailView
  AllerView.xcodeproj/project.pbxproj
  AllerView/View/AllergyDetailView.swift
  AllerView/View/LoadingView.swift
  AllerView/View/Model/GPTModel.swift
Labels: feat

#60 Add TextUtility
  AllerView.xcodeproj/project.pbxproj
  AllerView/Utility/TextUtility.swift
  AllerViewTests/TextUtilityTest.swift
Labels: feat

#61 Improve chat gpt prompt
  AllerView.xcodeproj/project.pbxproj
  AllerView/Extension/Bundle+Ext.swift
  AllerView/Network/OpenAI/Chat.swift
  AllerView/Service/OpenAIService.swift
  AllerView/Utility/TextUtility.swift
  AllerView/View/AllergyDetailView.swift
  AllerView/View/ImageCropView.swift
  AllerView/View/Model/GPTModel.swift
Labels: perf

#63 Refactor Project Structure
  AllerView.xcodeproj/project.pbxproj
  AllerView/Model/GPTResult.swift
  AllerView/Model/Product.swift
  AllerView/Network/OpenAI/Chat.swift
  AllerView/Network/OpenAI/Service.swift
  AllerView/View/AllergyDetailView.swift
  AllerView/View/Component/Chip.swift
  AllerView/View/ContentView.swift
  AllerView/View/ImageCropView.swift
  AllerView/View/MainView.swift
  AllerView/View/Model/GPTModel.swift
  AllerView/View/Model/GPTViewModel.swift
  AllerView/View/ScannerView.swift
Labels: refactor

#64 Add ScannerView Logics
  AllerView.xcodeproj/project.pbxproj
  AllerView/View/ImageCropView.swift
  AllerView/View/Model/RoundedRectLabel.swift
  AllerView/View/Model/ScannerViewController.swift
  AllerView/View/ScannerView.swift
Labels: feat

#68 Disable darkmode
  AllerView.xcodeproj/project.pbxproj
Labels: fix

#66 Add OnboardingView
  AllerView.xcodeproj/project.pbxproj
  AllerView/Resource/Assets.xcassets/OnboardingIllust.imageset/Contents.json
  AllerView/Resource/Assets.xcassets/OnboardingIllust.imageset/OnboardingIllust.svg
  AllerView/View/OnboardingView.swift
Labels: feat

#74 Modify Camera Authorization Logic
  AllerView.xcodeproj/project.pbxproj
  AllerView/View/ContentView.swift
Labels: refactor

#75 Add Readme Styles
  README.md
Labels: docs

#70 Add Haptics
  AllerView.xcodeproj/project.pbxproj
  AllerView/Utility/HapticUtility.swift
  AllerView/View/AllergyDetailView.swift
  AllerView/View/ScannerView.swift
Labels: feat

#76 Fix Camera View Issues
  AllerView/View/ScannerView.swift
  README.md
Labels: fix

#80 Modify User Camera Permission Notifying Text
  AllerView.xcodeproj/project.pbxproj
  AllerView/Resource/Assets.xcassets/AppIcon.appiconset/1024 1.png
  AllerView/Resource/Assets.xcassets/AppIcon.appiconset/1024 2.png
  AllerView/Resource/Assets.xcassets/AppIcon.appiconset/114 1.png
  AllerView/Resource/Assets.xcassets/AppIcon.appiconset/120 1.png
  AllerView/Resource/Assets.xcassets/AppIcon.appiconset/120 2.png
  AllerView/Resource/Assets.xcassets/AppIcon.appiconset/180 1.png
  AllerView/Resource/Assets.xcassets/AppIcon.appiconset/29.png
  AllerView/Resource/Assets.xcassets/AppIcon.appiconset/40 1.png
  AllerView/Resource/Assets.xcassets/AppIcon.appiconset/57.png
  AllerView/Resource/Assets.xcassets/AppIcon.appiconset/58 1.png
  AllerView/Resource/Assets.xcassets/AppIcon.appiconset/60 1.png
  AllerView/Resource/Assets.xcassets/AppIcon.appiconset/80 1.png
  AllerView/Resource/Assets.xcassets/AppIcon.appiconset/87 1.png
  AllerView/Resource/Assets.xcassets/AppIcon.appiconset/Contents.json
  AllerView/Resource/Assets.xcassets/AppIcon.appiconset/Group 74.png
  AllerView/View/ContentView.swift
  AllerView/View/OnboardingView.swift
Labels: refactor
